### ISSUE TITLE
Cannot assign values to tag fields

### ISSUE THREAD

**Issue by colomon** [avuserow/perl6-audio-taglib-simple#14]
Trying to assign a tag results in 

    Cannot assign to a readonly variable or a value

This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.

Think I'm using 0.0.7 of this module.

**Comment by avuserow** [comment]
This was fixed by a previous pull request but I didn't get the version bumped. Please try 0.0.8 now. Thanks.

**Comment by colomon** [comment]
Huh.  I'm a bit baffled by the complete sequence of events here, but I do have it working now.  Thanks!
